//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotvvmAcademy.Web.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UIResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UIResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DotvvmAcademy.Web.Resources.Localization.UIResources", typeof(UIResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you wonder how DotVVM works?
        ///It’s easy – all you need to know is HTML, C# and basics of CSS.
        ///We will explain everything to you in a few easy lessons..
        /// </summary>
        public static string App_Description {
            get {
                return ResourceManager.GetString("App_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a Lesson.
        /// </summary>
        public static string Base_ChooseLesson {
            get {
                return ResourceManager.GetString("Base_ChooseLesson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A series of short videos that show various features and controls of DotVVM..
        /// </summary>
        public static string Base_CoffeeDescription {
            get {
                return ResourceManager.GetString("Base_CoffeeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have a few minutes?&lt;br&gt;
        ///Watch &lt;strong&gt;DotVVM Coffee&lt;/strong&gt; videos!.
        /// </summary>
        public static string Base_CoffeeTitle {
            get {
                return ResourceManager.GetString("Base_CoffeeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correct.
        /// </summary>
        public static string Base_Correct_Solution {
            get {
                return ResourceManager.GetString("Base_Correct_Solution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentation.
        /// </summary>
        public static string Base_Documentation {
            get {
                return ResourceManager.GetString("Base_Documentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect.
        /// </summary>
        public static string Base_Incorrect_Solution {
            get {
                return ResourceManager.GetString("Base_Incorrect_Solution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interactive sample.
        /// </summary>
        public static string Base_InteractiveSample {
            get {
                return ResourceManager.GetString("Base_InteractiveSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to česky.
        /// </summary>
        public static string Base_Language_cs {
            get {
                return ResourceManager.GetString("Base_Language_cs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string Base_Language_en {
            get {
                return ResourceManager.GetString("Base_Language_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to русский.
        /// </summary>
        public static string Base_Language_ru {
            get {
                return ResourceManager.GetString("Base_Language_ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you wonder how DotVVM works?&lt;br&gt;
        ///It’s easy – all you need to know is &lt;strong&gt;HTML&lt;/strong&gt;, &lt;strong&gt;C#&lt;/strong&gt; and basics of &lt;strong&gt;CSS&lt;/strong&gt;.&lt;br&gt;
        ///We will explain everything to you in a few easy lessons..
        /// </summary>
        public static string Base_MainDescription {
            get {
                return ResourceManager.GetString("Base_MainDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn DotVVM&lt;br&gt; in &lt;b&gt;few&lt;/b&gt; minutes.
        /// </summary>
        public static string Base_MainTitle {
            get {
                return ResourceManager.GetString("Base_MainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This application is not supported on mobile browsers..
        /// </summary>
        public static string Base_MobileNotSupported {
            get {
                return ResourceManager.GetString("Base_MobileNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Samples.
        /// </summary>
        public static string Base_Samples {
            get {
                return ResourceManager.GetString("Base_Samples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutorials.
        /// </summary>
        public static string Base_Tutorials {
            get {
                return ResourceManager.GetString("Base_Tutorials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DotVVM Coffee.
        /// </summary>
        public static string Btn_Coffee {
            get {
                return ResourceManager.GetString("Btn_Coffee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string Btn_Copy {
            get {
                return ResourceManager.GetString("Btn_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy to Clipboard.
        /// </summary>
        public static string Btn_CopyTooltip {
            get {
                return ResourceManager.GetString("Btn_CopyTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Solution.
        /// </summary>
        public static string Btn_DownloadSolution {
            get {
                return ResourceManager.GetString("Btn_DownloadSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        public static string Btn_Finish {
            get {
                return ResourceManager.GetString("Btn_Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Solution.
        /// </summary>
        public static string Btn_GetSolution {
            get {
                return ResourceManager.GetString("Btn_GetSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Homepage.
        /// </summary>
        public static string Btn_Homepage {
            get {
                return ResourceManager.GetString("Btn_Homepage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Lesson.
        /// </summary>
        public static string Btn_NextLesson {
            get {
                return ResourceManager.GetString("Btn_NextLesson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate.
        /// </summary>
        public static string Btn_NextStep {
            get {
                return ResourceManager.GetString("Btn_NextStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate and Continue.
        /// </summary>
        public static string Btn_NextStepTooltip {
            get {
                return ResourceManager.GetString("Btn_NextStepTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string Btn_PreviousStep {
            get {
                return ResourceManager.GetString("Btn_PreviousStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Btn_Reset {
            get {
                return ResourceManager.GetString("Btn_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run DotVVM Academy.
        /// </summary>
        public static string Btn_StartCourse {
            get {
                return ResourceManager.GetString("Btn_StartCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start lesson.
        /// </summary>
        public static string Btn_StartLesson {
            get {
                return ResourceManager.GetString("Btn_StartLesson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string Btn_Success {
            get {
                return ResourceManager.GetString("Btn_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column.
        /// </summary>
        public static string DiagnosticList_ColumnHeader {
            get {
                return ResourceManager.GetString("DiagnosticList_ColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line.
        /// </summary>
        public static string DiagnosticList_LineHeader {
            get {
                return ResourceManager.GetString("DiagnosticList_LineHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string DiagnosticList_MessageHeader {
            get {
                return ResourceManager.GetString("DiagnosticList_MessageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We can&apos;t find the page you&apos;re looking for..
        /// </summary>
        public static string Error_404Message {
            get {
                return ResourceManager.GetString("Error_404Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Found.
        /// </summary>
        public static string Error_404Title {
            get {
                return ResourceManager.GetString("Error_404Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred on our side. Please try again later..
        /// </summary>
        public static string Error_500Message {
            get {
                return ResourceManager.GetString("Error_500Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Server Error.
        /// </summary>
        public static string Error_500Title {
            get {
                return ResourceManager.GetString("Error_500Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please evacuate the site in an orderly fashion..
        /// </summary>
        public static string Error_666Message {
            get {
                return ResourceManager.GetString("Error_666Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demonic Invasion in Progress.
        /// </summary>
        public static string Error_666Title {
            get {
                return ResourceManager.GetString("Error_666Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to Lessons.
        /// </summary>
        public static string Error_BackHome {
            get {
                return ResourceManager.GetString("Error_BackHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  has been successfully completed..
        /// </summary>
        public static string FinishDialog_DescriptionEnd {
            get {
                return ResourceManager.GetString("FinishDialog_DescriptionEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lesson .
        /// </summary>
        public static string FinishDialog_DescriptionStart {
            get {
                return ResourceManager.GetString("FinishDialog_DescriptionStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations!.
        /// </summary>
        public static string FinishDialog_Title {
            get {
                return ResourceManager.GetString("FinishDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en.
        /// </summary>
        public static string LangSwitcher_Class {
            get {
                return ResourceManager.GetString("LangSwitcher_Class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to images/Icons/Flag_US.svg.
        /// </summary>
        public static string LangSwitcher_Img {
            get {
                return ResourceManager.GetString("LangSwitcher_Img", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change language.
        /// </summary>
        public static string LangSwitcher_Title {
            get {
                return ResourceManager.GetString("LangSwitcher_Title", resourceCulture);
            }
        }
    }
}
