//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotvvmAcademy.Web.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UIResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UIResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DotvvmAcademy.Web.Resources.Localization.UIResources", typeof(UIResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a Lesson.
        /// </summary>
        public static string Base_ChooseLesson {
            get {
                return ResourceManager.GetString("Base_ChooseLesson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A series of short videos that show various features and controls of DotVVM..
        /// </summary>
        public static string Base_CoffeeDescription {
            get {
                return ResourceManager.GetString("Base_CoffeeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have a few minutes?&lt;br&gt;
        ///Watch &lt;strong&gt;DotVVM Coffee&lt;/strong&gt; videos!.
        /// </summary>
        public static string Base_CoffeeTitle {
            get {
                return ResourceManager.GetString("Base_CoffeeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentation.
        /// </summary>
        public static string Base_Documentation {
            get {
                return ResourceManager.GetString("Base_Documentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you wonder how DotVVM works?&lt;br&gt;
        ///It’s easy – all you need to know is &lt;strong&gt;HTML&lt;/strong&gt;, &lt;strong&gt;C#&lt;/strong&gt; and basics of &lt;strong&gt;CSS&lt;/strong&gt;.&lt;br&gt;
        ///We will explain everything to you in a few easy lessons..
        /// </summary>
        public static string Base_MainDescription {
            get {
                return ResourceManager.GetString("Base_MainDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn DotVVM&lt;br&gt; in &lt;b&gt;few&lt;/b&gt; minutes.
        /// </summary>
        public static string Base_MainTitle {
            get {
                return ResourceManager.GetString("Base_MainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Samples.
        /// </summary>
        public static string Base_Samples {
            get {
                return ResourceManager.GetString("Base_Samples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutorials.
        /// </summary>
        public static string Base_Tutorials {
            get {
                return ResourceManager.GetString("Base_Tutorials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DotVVM Coffee.
        /// </summary>
        public static string Btn_Coffee {
            get {
                return ResourceManager.GetString("Btn_Coffee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        public static string Btn_Finish {
            get {
                return ResourceManager.GetString("Btn_Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Btn_NextStep {
            get {
                return ResourceManager.GetString("Btn_NextStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string Btn_PreviousStep {
            get {
                return ResourceManager.GetString("Btn_PreviousStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run DotVVM Academy.
        /// </summary>
        public static string Btn_StartCourse {
            get {
                return ResourceManager.GetString("Btn_StartCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start lesson.
        /// </summary>
        public static string Btn_StartLesson {
            get {
                return ResourceManager.GetString("Btn_StartLesson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en.
        /// </summary>
        public static string LangSwitcher_Class {
            get {
                return ResourceManager.GetString("LangSwitcher_Class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to images/Icons/Flag_US.svg.
        /// </summary>
        public static string LangSwitcher_Img {
            get {
                return ResourceManager.GetString("LangSwitcher_Img", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change language.
        /// </summary>
        public static string LangSwitcher_Title {
            get {
                return ResourceManager.GetString("LangSwitcher_Title", resourceCulture);
            }
        }
    }
}
