//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotvvmAcademy.LessonXmlParser {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LessonXmlElements {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal LessonXmlElements() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DotvvmAcademy.LessonXmlParser.LessonXmlElements", typeof(LessonXmlElements).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to AllowedMethod.
        /// </summary>
        public static string AllowedMethodElement {
            get {
                return ResourceManager.GetString("AllowedMethodElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to AllowedMethodsCalled.
        /// </summary>
        public static string AllowedMethodsCalledElement {
            get {
                return ResourceManager.GetString("AllowedMethodsCalledElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to AllowedType.
        /// </summary>
        public static string AllowedTypeElement {
            get {
                return ResourceManager.GetString("AllowedTypeElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to AllowedTypesConstructed.
        /// </summary>
        public static string AllowedTypesConstructedElement {
            get {
                return ResourceManager.GetString("AllowedTypesConstructedElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to CodeDependencies.
        /// </summary>
        public static string CodeDependenciesElement {
            get {
                return ResourceManager.GetString("CodeDependenciesElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to CodeDependency.
        /// </summary>
        public static string CodeDependencyElement {
            get {
                return ResourceManager.GetString("CodeDependencyElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Description.
        /// </summary>
        public static string DescriptionElement {
            get {
                return ResourceManager.GetString("DescriptionElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to FinalCode.
        /// </summary>
        public static string FinalCodeElement {
            get {
                return ResourceManager.GetString("FinalCodeElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to ShadowBoxDescription.
        /// </summary>
        public static string ShadowBoxDescriptionElement {
            get {
                return ResourceManager.GetString("ShadowBoxDescriptionElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to StartupCode.
        /// </summary>
        public static string StartupCodeElement {
            get {
                return ResourceManager.GetString("StartupCodeElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Step.
        /// </summary>
        public static string StepElement {
            get {
                return ResourceManager.GetString("StepElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Steps.
        /// </summary>
        public static string StepsElement {
            get {
                return ResourceManager.GetString("StepsElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Type.
        /// </summary>
        public static string StepTypeAttribute {
            get {
                return ResourceManager.GetString("StepTypeAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to CsharpCode.
        /// </summary>
        public static string StepTypeCsharpCode {
            get {
                return ResourceManager.GetString("StepTypeCsharpCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to DothtmlCode.
        /// </summary>
        public static string StepTypeDothtmlCode {
            get {
                return ResourceManager.GetString("StepTypeDothtmlCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Info.
        /// </summary>
        public static string StepTypeInfo {
            get {
                return ResourceManager.GetString("StepTypeInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Title.
        /// </summary>
        public static string TitleElement {
            get {
                return ResourceManager.GetString("TitleElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to ValidationKey.
        /// </summary>
        public static string ValidationKeyElement {
            get {
                return ResourceManager.GetString("ValidationKeyElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to ValidatorsNamespace.
        /// </summary>
        public static string ValidatorsNamespaceElement {
            get {
                return ResourceManager.GetString("ValidatorsNamespaceElement", resourceCulture);
            }
        }
    }
}
