//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotvvmAcademy.Steps.Validation.Validators.Lesson2 {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lesson2Texts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lesson2Texts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DotvvmAcademy.Steps.Validation.Validators.Lesson2.Lesson2Texts", typeof(Lesson2Texts).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There should be a Button control in the page!.
        /// </summary>
        public static string AddTaskButtonControlError {
            get {
                return ResourceManager.GetString("AddTaskButtonControlError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When creating a task, use the AddedTaskTitle as a title of the task!.
        /// </summary>
        public static string AddTaskInvalidTaskText {
            get {
                return ResourceManager.GetString("AddTaskInvalidTaskText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The AddTask() method should add one task!.
        /// </summary>
        public static string AddTaskShouldAddTaskObject {
            get {
                return ResourceManager.GetString("AddTaskShouldAddTaskObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There should be a TextBox control in the page!.
        /// </summary>
        public static string AddTaskTextBoxControlError {
            get {
                return ResourceManager.GetString("AddTaskTextBoxControlError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to reset the AddedTaskTitle property to an empty string after you create a task!.
        /// </summary>
        public static string AddTaskTitleNotReset {
            get {
                return ResourceManager.GetString("AddTaskTitleNotReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must set the Text property of the Button!.
        /// </summary>
        public static string ButtonDoesNotHaveText {
            get {
                return ResourceManager.GetString("ButtonDoesNotHaveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The CompleteTask() method should set the IsCompleted to true!.
        /// </summary>
        public static string CompleteTaskMethodError {
            get {
                return ResourceManager.GetString("CompleteTaskMethodError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The class attribute doesn&apos;t contain the binding!.
        /// </summary>
        public static string InvalidClassBinding {
            get {
                return ResourceManager.GetString("InvalidClassBinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The expression in the class attribute is not correct! If the task is completed, the CSS class should be &apos;task-completed&apos;, otherwise it should be &apos;task&apos;. .
        /// </summary>
        public static string InvalidClassExpressionBinding {
            get {
                return ResourceManager.GetString("InvalidClassExpressionBinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Visible binding expression is not correct! Didn&apos;t you forget to negate the expression?.
        /// </summary>
        public static string InvalidVisibleBinding {
            get {
                return ResourceManager.GetString("InvalidVisibleBinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The LinkButton control wasn&apos;t found inside the Repeater control!.
        /// </summary>
        public static string LinkButtonNotFound {
            get {
                return ResourceManager.GetString("LinkButtonNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The DataSource property of the Repeater should be bound to the Tasks property!.
        /// </summary>
        public static string RepeaterBindingError {
            get {
                return ResourceManager.GetString("RepeaterBindingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There should be a Repeater control in the page!.
        /// </summary>
        public static string RepeaterControlError {
            get {
                return ResourceManager.GetString("RepeaterControlError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Repeater should contain a div element with the &quot;task&quot; CSS class..
        /// </summary>
        public static string RepeaterTemplateMissingDivError {
            get {
                return ResourceManager.GetString("RepeaterTemplateMissingDivError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The TextBox should be bound the the AddedTaskTitle property!.
        /// </summary>
        public static string TextBoxBindingError {
            get {
                return ResourceManager.GetString("TextBoxBindingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Title is not rendered inside the Repeater control!.
        /// </summary>
        public static string TitleBindingNotFound {
            get {
                return ResourceManager.GetString("TitleBindingNotFound", resourceCulture);
            }
        }
    }
}
