namespace DotvvmAcademy.Meta.Syntax
{
    public enum NameNodeKind
    {
        Bad,
        Identifier,
        BoolType,
        ByteType,
        SByteType,
        IntType,
        UIntType,
        ShortType,
        UShortType,
        LongType,
        ULongType,
        FloatType,
        DoubleType,
        DecimalType,
        StringType,
        CharType,
        ObjectType,
        VoidType,
        Generic,
        Qualified,
        NestedType,
        ConstructedType,
        TypeArgumentList,
        PointerType,
        ArrayType,
        Member
    }
}