//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotvvmAcademy.Validation.Dothtml {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DotvvmAcademy.Validation.Dothtml.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &apos;{0}&apos; must be set using a binding..
        /// </summary>
        public static string ERR_MandatoryBinding {
            get {
                return ResourceManager.GetString("ERR_MandatoryBinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &apos;{0}&apos; must be set using a hardcoded value..
        /// </summary>
        public static string ERR_MandatoryHardcodedValue {
            get {
                return ResourceManager.GetString("ERR_MandatoryHardcodedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directive &apos;{0}&apos; must have a type as its argument..
        /// </summary>
        public static string ERR_MandatoryTypeDirective {
            get {
                return ResourceManager.GetString("ERR_MandatoryTypeDirective", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A &apos;{0}&apos; control must be at &apos;{1}&apos;..
        /// </summary>
        public static string ERR_MissingControl {
            get {
                return ResourceManager.GetString("ERR_MissingControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This node must contain a &apos;{0}&apos; control..
        /// </summary>
        public static string ERR_MissingControlLocal {
            get {
                return ResourceManager.GetString("ERR_MissingControlLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directive &apos;{0}&apos; must be set..
        /// </summary>
        public static string ERR_MissingDirective {
            get {
                return ResourceManager.GetString("ERR_MissingDirective", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A &apos;{0}&apos; node must be at &apos;{1}&apos;..
        /// </summary>
        public static string ERR_MissingNode {
            get {
                return ResourceManager.GetString("ERR_MissingNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This node must contain a &apos;{0}&apos; node..
        /// </summary>
        public static string ERR_MissingNodeLocal {
            get {
                return ResourceManager.GetString("ERR_MissingNodeLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; property must be set at &apos;{1}&apos;..
        /// </summary>
        public static string ERR_MissingProperty {
            get {
                return ResourceManager.GetString("ERR_MissingProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This node must have its &apos;{0}&apos; property set..
        /// </summary>
        public static string ERR_MissingPropertyLocal {
            get {
                return ResourceManager.GetString("ERR_MissingPropertyLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binding must be of kind &apos;{0}&apos;..
        /// </summary>
        public static string ERR_WrongBindingKind {
            get {
                return ResourceManager.GetString("ERR_WrongBindingKind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &apos;{0}&apos; must be bound to &apos;{1}&apos;..
        /// </summary>
        public static string ERR_WrongBindingValue {
            get {
                return ResourceManager.GetString("ERR_WrongBindingValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control must be of type &apos;{0}&apos;..
        /// </summary>
        public static string ERR_WrongControlType {
            get {
                return ResourceManager.GetString("ERR_WrongControlType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There must be {0} &apos;{1}&apos; controls..
        /// </summary>
        public static string ERR_WrongCount {
            get {
                return ResourceManager.GetString("ERR_WrongCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hardcoded value must be &apos;{0}&apos;..
        /// </summary>
        public static string ERR_WrongHardcodedValue {
            get {
                return ResourceManager.GetString("ERR_WrongHardcodedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control&apos;s raw content must be &apos;{0}&apos;..
        /// </summary>
        public static string ERR_WrongRawContent {
            get {
                return ResourceManager.GetString("ERR_WrongRawContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control in its raw text form muse be &apos;{0}&apos;..
        /// </summary>
        public static string ERR_WrongRawText {
            get {
                return ResourceManager.GetString("ERR_WrongRawText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directive must reference type &apos;{0}&apos;..
        /// </summary>
        public static string ERR_WrongTypeDirectiveArgument {
            get {
                return ResourceManager.GetString("ERR_WrongTypeDirectiveArgument", resourceCulture);
            }
        }
    }
}
