//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotvvmAcademy.Validation.Dothtml {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DotvvmAcademy.Validation.Dothtml.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This control is missing a control of type &apos;{0}&apos;..
        /// </summary>
        public static string ERR_MissingControl {
            get {
                return ResourceManager.GetString("ERR_MissingControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The document root is missing a control of type &apos;{0}&apos;..
        /// </summary>
        public static string ERR_MissingControlRoot {
            get {
                return ResourceManager.GetString("ERR_MissingControlRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; directive must be set..
        /// </summary>
        public static string ERR_MissingDirective {
            get {
                return ResourceManager.GetString("ERR_MissingDirective", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This control is missing an HTML &apos;{0}&apos; element..
        /// </summary>
        public static string ERR_MissingElement {
            get {
                return ResourceManager.GetString("ERR_MissingElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The document root is missing an HTML &apos;{0}&apos; element..
        /// </summary>
        public static string ERR_MissingElementRoot {
            get {
                return ResourceManager.GetString("ERR_MissingElementRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This control must have its &apos;{0}&apos; property set..
        /// </summary>
        public static string ERR_MissingProperty {
            get {
                return ResourceManager.GetString("ERR_MissingProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This property must be bound to: &apos;{0}&apos;..
        /// </summary>
        public static string ERR_WrongBindingValue {
            get {
                return ResourceManager.GetString("ERR_WrongBindingValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This control must contain {0} controls of type &apos;{1}&apos;..
        /// </summary>
        public static string ERR_WrongControlCount {
            get {
                return ResourceManager.GetString("ERR_WrongControlCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The document root must contain {0} controls of type &apos;{1}&apos;..
        /// </summary>
        public static string ERR_WrongControlCountRoot {
            get {
                return ResourceManager.GetString("ERR_WrongControlCountRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control must be of type &apos;{0}&apos;..
        /// </summary>
        public static string ERR_WrongControlType {
            get {
                return ResourceManager.GetString("ERR_WrongControlType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This control must contain {0} &apos;{1}&apos; elements..
        /// </summary>
        public static string ERR_WrongElementCount {
            get {
                return ResourceManager.GetString("ERR_WrongElementCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The document root must contain {0} &apos;{1}&apos; elements..
        /// </summary>
        public static string ERR_WrongElementCountRoot {
            get {
                return ResourceManager.GetString("ERR_WrongElementCountRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This property must be set to &apos;{0}&apos;..
        /// </summary>
        public static string ERR_WrongHardcodedValue {
            get {
                return ResourceManager.GetString("ERR_WrongHardcodedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This control must contain: &apos;{0}&apos;..
        /// </summary>
        public static string ERR_WrongRawContent {
            get {
                return ResourceManager.GetString("ERR_WrongRawContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This control must be declared in this way: &apos;{0}&apos;..
        /// </summary>
        public static string ERR_WrongRawText {
            get {
                return ResourceManager.GetString("ERR_WrongRawText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This property must be set using {0}..
        /// </summary>
        public static string ERR_WrongSetter {
            get {
                return ResourceManager.GetString("ERR_WrongSetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; directive must reference type &apos;{1}&apos;..
        /// </summary>
        public static string ERR_WrongTypeDirectiveArgument {
            get {
                return ResourceManager.GetString("ERR_WrongTypeDirectiveArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a command binding.
        /// </summary>
        public static string Setter_CommandBinding {
            get {
                return ResourceManager.GetString("Setter_CommandBinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a control command binding.
        /// </summary>
        public static string Setter_ControlCommandBinding {
            get {
                return ResourceManager.GetString("Setter_ControlCommandBinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a control property binding.
        /// </summary>
        public static string Setter_ControlPropertyBinding {
            get {
                return ResourceManager.GetString("Setter_ControlPropertyBinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a hard-coded value.
        /// </summary>
        public static string Setter_HardcodedValue {
            get {
                return ResourceManager.GetString("Setter_HardcodedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , or.
        /// </summary>
        public static string Setter_Or {
            get {
                return ResourceManager.GetString("Setter_Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a resource binding.
        /// </summary>
        public static string Setter_ResourceBinding {
            get {
                return ResourceManager.GetString("Setter_ResourceBinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a static command binding.
        /// </summary>
        public static string Setter_StaticCommandBinding {
            get {
                return ResourceManager.GetString("Setter_StaticCommandBinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a value binding.
        /// </summary>
        public static string Setter_ValueBinding {
            get {
                return ResourceManager.GetString("Setter_ValueBinding", resourceCulture);
            }
        }
    }
}
