//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotvvmAcademy.Lessons {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LessonNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LessonNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DotvvmAcademy.Lessons.LessonNames", typeof(LessonNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentation.
        /// </summary>
        public static string DocumentationText {
            get {
                return ResourceManager.GetString("DocumentationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coming Soon.
        /// </summary>
        public static string IsCreatedLessonBtnText {
            get {
                return ResourceManager.GetString("IsCreatedLessonBtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat Lesson.
        /// </summary>
        public static string IsFinishedLessonBtnText {
            get {
                return ResourceManager.GetString("IsFinishedLessonBtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string IsVisitedLessonBtnText {
            get {
                return ResourceManager.GetString("IsVisitedLessonBtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Understand basic principles of DotVVM&lt;br /&gt;and the MVVM pattern..
        /// </summary>
        public static string Lesson1_Desc {
            get {
                return ResourceManager.GetString("Lesson1_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dotvvm elementary 1.
        /// </summary>
        public static string Lesson1_Title {
            get {
                return ResourceManager.GetString("Lesson1_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn how to use the Repeater control&lt;br /&gt; and how to work with collections..
        /// </summary>
        public static string Lesson2_Desc {
            get {
                return ResourceManager.GetString("Lesson2_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dotvvm elementary 2.
        /// </summary>
        public static string Lesson2_Title {
            get {
                return ResourceManager.GetString("Lesson2_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try out working with the DataContext property and advanced form controls like ComboBox and RadioButton..
        /// </summary>
        public static string Lesson3_Desc {
            get {
                return ResourceManager.GetString("Lesson3_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dotvvm intermediate.
        /// </summary>
        public static string Lesson3_Title {
            get {
                return ResourceManager.GetString("Lesson3_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn how validation works..
        /// </summary>
        public static string Lesson4_Desc {
            get {
                return ResourceManager.GetString("Lesson4_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dotvvm intermediate.
        /// </summary>
        public static string Lesson4_Title {
            get {
                return ResourceManager.GetString("Lesson4_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to naučte se dotvvm&lt;br /&gt; za &lt;strong&gt;pár&lt;/strong&gt; minut.
        /// </summary>
        public static string MainTitle {
            get {
                return ResourceManager.GetString("MainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string NextBtnText {
            get {
                return ResourceManager.GetString("NextBtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ultimátní online kurz webového českého&lt;br /&gt;frameworku bez nutnosti psaní tun Javascriptu!&lt;br /&gt;Všechno co potřebujete vědět je &lt;strong&gt;C#&lt;/strong&gt;, &lt;strong&gt;HTML&lt;/strong&gt; a &lt;strong&gt;CSS&lt;/strong&gt;!.
        /// </summary>
        public static string OnlineCourseText {
            get {
                return ResourceManager.GetString("OnlineCourseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string PreviousBtnText {
            get {
                return ResourceManager.GetString("PreviousBtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string ResetBtn {
            get {
                return ResourceManager.GetString("ResetBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Samples.
        /// </summary>
        public static string SamplesText {
            get {
                return ResourceManager.GetString("SamplesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Correct Code.
        /// </summary>
        public static string ShowCorrectCodeBtn {
            get {
                return ResourceManager.GetString("ShowCorrectCodeBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Lesson.
        /// </summary>
        public static string StartLessonBtnText {
            get {
                return ResourceManager.GetString("StartLessonBtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step.
        /// </summary>
        public static string StepBtnText {
            get {
                return ResourceManager.GetString("StepBtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutorials.
        /// </summary>
        public static string TutorialsText {
            get {
                return ResourceManager.GetString("TutorialsText", resourceCulture);
            }
        }
    }
}
