//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotvvmAcademy.Lessons {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LessonNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LessonNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DotvvmAcademy.Lessons.LessonNames", typeof(LessonNames).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dokumentation.
        /// </summary>
        public static string DocumentationText {
            get {
                return ResourceManager.GetString("DocumentationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coming Soon.
        /// </summary>
        public static string IsCreatedLessonBtnText {
            get {
                return ResourceManager.GetString("IsCreatedLessonBtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat Lesson.
        /// </summary>
        public static string IsFinishedLessonBtnText {
            get {
                return ResourceManager.GetString("IsFinishedLessonBtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string IsVisitedLessonBtnText {
            get {
                return ResourceManager.GetString("IsVisitedLessonBtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Understand basic principles of DotVVM and MVVM pattern..
        /// </summary>
        public static string Lesson1 {
            get {
                return ResourceManager.GetString("Lesson1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn how to use the &lt;code&gt;Repeater&lt;/code&gt; control and how to work with collections..
        /// </summary>
        public static string Lesson2 {
            get {
                return ResourceManager.GetString("Lesson2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try out working with advanced form controls like &lt;code&gt;ComboBox&lt;/code&gt; and &lt;code&gt;RadioButton&lt;/code&gt;..
        /// </summary>
        public static string Lesson3 {
            get {
                return ResourceManager.GetString("Lesson3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn how validation works and &lt;code&gt;DataContext&lt;/code&gt; works..
        /// </summary>
        public static string Lesson4 {
            get {
                return ResourceManager.GetString("Lesson4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lesson.
        /// </summary>
        public static string LessonText {
            get {
                return ResourceManager.GetString("LessonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string NextBtnText {
            get {
                return ResourceManager.GetString("NextBtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to online course.
        /// </summary>
        public static string OnlineCourseText {
            get {
                return ResourceManager.GetString("OnlineCourseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Samples.
        /// </summary>
        public static string SamplesText {
            get {
                return ResourceManager.GetString("SamplesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Lesson.
        /// </summary>
        public static string StartLessonBtnText {
            get {
                return ResourceManager.GetString("StartLessonBtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step.
        /// </summary>
        public static string StepBtnText {
            get {
                return ResourceManager.GetString("StepBtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutorials.
        /// </summary>
        public static string TutorialsText {
            get {
                return ResourceManager.GetString("TutorialsText", resourceCulture);
            }
        }
    }
}
