//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotvvmAcademy.Lessons {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LessonNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LessonNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DotvvmAcademy.Lessons.LessonNames", typeof(LessonNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a Lesson.
        /// </summary>
        public static string Base_ChooseLesson {
            get {
                return ResourceManager.GetString("Base_ChooseLesson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A series of short videos that show various features and controls of DotVVM..
        /// </summary>
        public static string Base_CoffeeDesc {
            get {
                return ResourceManager.GetString("Base_CoffeeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have a few minutes?&lt;br&gt;
        ///Watch &lt;strong&gt;DotVVM Coffee&lt;/strong&gt; videos!.
        /// </summary>
        public static string Base_CoffeeTitle {
            get {
                return ResourceManager.GetString("Base_CoffeeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you wonder how DotVVM works?&lt;br&gt;
        ///It’s easy – all you need to know is &lt;strong&gt;HTML&lt;/strong&gt;, &lt;strong&gt;C#&lt;/strong&gt; and basics of &lt;strong&gt;CSS&lt;/strong&gt;.&lt;br&gt;
        ///We will explain everything to you in a few easy lessons..
        /// </summary>
        public static string Base_MainDesc {
            get {
                return ResourceManager.GetString("Base_MainDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn DotVVM&lt;br&gt; in &lt;b&gt;few&lt;/b&gt; minutes.
        /// </summary>
        public static string Base_MainTitle {
            get {
                return ResourceManager.GetString("Base_MainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DotVVM Coffee.
        /// </summary>
        public static string Btn_Coffee {
            get {
                return ResourceManager.GetString("Btn_Coffee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run DotVVM Academy.
        /// </summary>
        public static string Btn_StartCourse {
            get {
                return ResourceManager.GetString("Btn_StartCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentation.
        /// </summary>
        public static string DocumentationText {
            get {
                return ResourceManager.GetString("DocumentationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coming Soon.
        /// </summary>
        public static string IsCreatedLessonBtnText {
            get {
                return ResourceManager.GetString("IsCreatedLessonBtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat Lesson.
        /// </summary>
        public static string IsFinishedLessonBtnText {
            get {
                return ResourceManager.GetString("IsFinishedLessonBtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string IsVisitedLessonBtnText {
            get {
                return ResourceManager.GetString("IsVisitedLessonBtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You’ll understand the basics of DotVVM and MVVM design pattern..
        /// </summary>
        public static string Lesson1_Desc {
            get {
                return ResourceManager.GetString("Lesson1_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Lesson 1: Basic principles.
        /// </summary>
        public static string Lesson1_Title {
            get {
                return ResourceManager.GetString("Lesson1_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You’ll see the Repeater control and how to work with collections..
        /// </summary>
        public static string Lesson2_Desc {
            get {
                return ResourceManager.GetString("Lesson2_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lesson 2: Collections.
        /// </summary>
        public static string Lesson2_Title {
            get {
                return ResourceManager.GetString("Lesson2_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You’ll use DotVVM ComboBox and RadioButton and learn about the DataContext property..
        /// </summary>
        public static string Lesson3_Desc {
            get {
                return ResourceManager.GetString("Lesson3_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lesson 3: Forms in DotVVM.
        /// </summary>
        public static string Lesson3_Title {
            get {
                return ResourceManager.GetString("Lesson3_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn how validation works..
        /// </summary>
        public static string Lesson4_Desc {
            get {
                return ResourceManager.GetString("Lesson4_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lesson 4: Validation.
        /// </summary>
        public static string Lesson4_Title {
            get {
                return ResourceManager.GetString("Lesson4_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en.
        /// </summary>
        public static string LocalizeClass {
            get {
                return ResourceManager.GetString("LocalizeClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to images/Icons/Flag_US.svg.
        /// </summary>
        public static string LocalizeImg {
            get {
                return ResourceManager.GetString("LocalizeImg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change language.
        /// </summary>
        public static string LocalizeMainTitle {
            get {
                return ResourceManager.GetString("LocalizeMainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string NextBtnText {
            get {
                return ResourceManager.GetString("NextBtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string PreviousBtnText {
            get {
                return ResourceManager.GetString("PreviousBtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string ResetBtn {
            get {
                return ResourceManager.GetString("ResetBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Samples.
        /// </summary>
        public static string SamplesText {
            get {
                return ResourceManager.GetString("SamplesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Correct Code.
        /// </summary>
        public static string ShowCorrectCodeBtn {
            get {
                return ResourceManager.GetString("ShowCorrectCodeBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Lesson.
        /// </summary>
        public static string StartLessonBtnText {
            get {
                return ResourceManager.GetString("StartLessonBtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step.
        /// </summary>
        public static string StepBtnText {
            get {
                return ResourceManager.GetString("StepBtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutorials.
        /// </summary>
        public static string TutorialsText {
            get {
                return ResourceManager.GetString("TutorialsText", resourceCulture);
            }
        }
    }
}
