//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotvvmAcademy.Validation.CSharp {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DotvvmAcademy.Validation.CSharp.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol &apos;{0}&apos; must have no &apos;{1}&apos; attribute..
        /// </summary>
        public static string ERR_ForbiddenAttribute {
            get {
                return ResourceManager.GetString("ERR_ForbiddenAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol &apos;{0}&apos; must have a &apos;{1}&apos; attribute..
        /// </summary>
        public static string ERR_MissingAttribute {
            get {
                return ResourceManager.GetString("ERR_MissingAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &apos;{0}&apos; must have a &apos;{1}&apos; getter..
        /// </summary>
        public static string ERR_MissingGetter {
            get {
                return ResourceManager.GetString("ERR_MissingGetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; must implement the &apos;{1}&apos; interface..
        /// </summary>
        public static string ERR_MissingInterfaceImplementation {
            get {
                return ResourceManager.GetString("ERR_MissingInterfaceImplementation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &apos;{0}&apos; must be read-only..
        /// </summary>
        public static string ERR_MissingReadonly {
            get {
                return ResourceManager.GetString("ERR_MissingReadonly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &apos;{0}&apos; must have a &apos;{1}&apos; setter..
        /// </summary>
        public static string ERR_MissingSetter {
            get {
                return ResourceManager.GetString("ERR_MissingSetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol &apos;{0}&apos; has to declare accessibility &apos;{1}&apos;..
        /// </summary>
        public static string ERR_WrongAccessibility {
            get {
                return ResourceManager.GetString("ERR_WrongAccessibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; must have &apos;{1}&apos; as its base type..
        /// </summary>
        public static string ERR_WrongBaseType {
            get {
                return ResourceManager.GetString("ERR_WrongBaseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There must be &apos;{0}&apos; of &apos;{1}&apos;..
        /// </summary>
        public static string ERR_WrongCount {
            get {
                return ResourceManager.GetString("ERR_WrongCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &apos;{0}&apos; must be of type &apos;{1}&apos;..
        /// </summary>
        public static string ERR_WrongFieldType {
            get {
                return ResourceManager.GetString("ERR_WrongFieldType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter must be of type &apos;{0}&apos;..
        /// </summary>
        public static string ERR_WrongParameterType {
            get {
                return ResourceManager.GetString("ERR_WrongParameterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method &apos;{0}&apos; must have &apos;{1}&apos; parameters..
        /// </summary>
        public static string ERR_WrongParemeterCount {
            get {
                return ResourceManager.GetString("ERR_WrongParemeterCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &apos;{0}&apos; must be of type &apos;{1}&apos;..
        /// </summary>
        public static string ERR_WrongPropertyType {
            get {
                return ResourceManager.GetString("ERR_WrongPropertyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method &apos;{0}&apos; must return a &apos;{1}&apos;..
        /// </summary>
        public static string ERR_WrongReturnType {
            get {
                return ResourceManager.GetString("ERR_WrongReturnType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; has to be a &apos;{1}&apos;..
        /// </summary>
        public static string ERR_WrongTypeKind {
            get {
                return ResourceManager.GetString("ERR_WrongTypeKind", resourceCulture);
            }
        }
    }
}
