//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotvvmAcademy.Steps.Validation.Validators.Lesson4 {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lesson4Texts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lesson4Texts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DotvvmAcademy.Steps.Validation.Validators.Lesson4.Lesson4Texts", typeof(Lesson4Texts).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should add Validator.InvalidCssClass property to all div elements!.
        /// </summary>
        public static string AllDivsMustHaveInvalidCssClass {
            get {
                return ResourceManager.GetString("AllDivsMustHaveInvalidCssClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property {0} should be {1} attribute!.
        /// </summary>
        public static string AttributeMissing {
            get {
                return ResourceManager.GetString("AttributeMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should delete the Validator.InvalidCssClass property from the div elements. It is set on the parent level now..
        /// </summary>
        public static string ChildDivsDontNeedInvalidCssClassAnymore {
            get {
                return ResourceManager.GetString("ChildDivsDontNeedInvalidCssClassAnymore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The condition is not correct!.
        /// </summary>
        public static string IncorrectValidationRule {
            get {
                return ResourceManager.GetString("IncorrectValidationRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should wrap the div elements with one form element!.
        /// </summary>
        public static string WrapDivsInForm {
            get {
                return ResourceManager.GetString("WrapDivsInForm", resourceCulture);
            }
        }
    }
}
